### ISSUE TITLE
Gewijzigde regelgeving

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/ontology#16]
ToelatingVooronderzoek zou ToelatingVooronderzoekWV moeten worden
MeldingVooronderzoek zou ToelatingVooronderzoekVI moeten worden

Hoe pakken we dit best aan? Kunnen we die oude ergens als deprecated flaggen?

**Comment by koenedaele** [comment]
Die oude ToelatingVooronderzoek is een class URI. Op zich wijzigt daar niets behalve het label. Dus, die URI kan dezelfde blijven aangezien het concept ook niet gewijzigd is.

**Comment by koenedaele** [comment]
Die tweede is trickier. Er zijn ook properties gedefinieerd met als domain MeldingVooronderzoek.

Optie 1: We zien de verschillen tussen een MeldingVooronderzoek en een ToelatingVooronderzoekVI als semantiek en passen net zoals bij de ToelatingVooronderzoek ook gewoon het label aan. Dan moeten we de properties ook niet aanpassen.
Optie 2: We zien de verschillen als voldoende betekenisvol en maken een nieuwe class. De oude krijgt dan de status "archaic" (denk ik, moet de correcte term eens opzoeken). De twee properties moeten dan ofwel ook hernoemd worden ofwel passen we gewoon het domain aan.

In alle verhalen die ik hoor is het verschil tussen de verschillende dingen allemaal meer een ander label dan echt betekenis. Dus, ik ben geneigd voor optie 1 te gaan en ook hier gewoon wat labels aan te passen. Uiteindelijk blijft in RDF een URI iets betekenisloos.

**Comment by claeyswo** [comment]
Bump. Mag ik die zaken, aangezien nog nergens extern verspreid, dan gewoon hernoemen?

**Comment by koenedaele** [comment]
Nee, maar ik maak een oplossing met owl:sameAs. Even geduld
