### ISSUE TITLE
Authentieke bronnen Archeologie

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/ontology#2]
We need to add Classes for the Authentieke Bronnen that deal with Archeologie.

@kmillet Could you please make a list of all the authentieke bronnen en the URI's where they will be living once finished?

**Comment by kmillet** [comment]
I will meet tomorrow with Wouter and Jolijn and provide you with the list afterwards.

**Comment by kmillet** [comment]
This is the list, more extended info you can find on https://github.com/OnroerendErfgoed/archeologieportaal/issues/8

**Archeologieportaal (geen authentieke born)
**
uri: https://id.erfgoed.net/archeologie

**Meldingen vooronderzoek (authentieke bron)
**
uri: https://id.erfgoed.net/archeologie/meldingen_vooronderzoek

**Meldingen aanvang (authentieke bron)
**
_uris in het kader van bouwwerken
_
https://id.erfgoed.net/archeologie/meldingen_aanvang/bouwwerken/vooronderzoek
https://id.erfgoed.net/archeologie/meldingen_aanvang/bouwwerken/opgraving

_uris in het kader van wetenschappelijke vraagstelling
_
https://id.erfgoed.net/archeologie/meldingen_aanvang/wetenschappelijke_vraagstelling/vooronderzoek
https://id.erfgoed.net/archeologie/meldingen_aanvang/wetenschappelijke_vraagstelling/opgraving


**Notas (authentieke bron)
**

_Uri's
_
https://id.erfgoed.net/archeologie/notas
https://id.erfgoed.net/archeologie/archeologienotas


**Rapporten en eindverslagen (authentieke bron)
**
_uris in het kader van bouwwerken
_
https://id.erfgoed.net/archeologie/archeologierapporten/bouwwerken
https://id.erfgoed.net/archeologie/eindverslagen/bouwwerken

_uris in het kader van wetenschappelijke vraagstelling
_
https://id.erfgoed.net/archeologie/archeologierapporten/wetenschappelijke_vraagstelling/vooronderzoek
https://id.erfgoed.net/archeologie/archeologierapporten/wetenschappelijke_vraagstelling/opgraving
https://id.erfgoed.net/archeologie/eindverslagen/wetenschappelijke_vraagstelling/vooronderzoek
https://id.erfgoed.net/archeologie/eindverslagen/wetenschappelijke_vraagstelling/opgraving


**Toelatingen (Authentieke bron)
**
_uris
_
https://id.erfgoed.net/archeologie/toelatingen/opgraving
https://id.erfgoed.net/archeologie/toelatingen/vooronderzoek


**Toevalsvondsten (Authentieke bron)
**
https://id.erfgoed.net/archeologie/toevalsvondsten

**Comment by koenedaele** [comment]
> **Archeologieportaal (geen authentieke born)**
>
>_uri:_
>
> > https://id.erfgoed.net/archeologie

Why does this URI exist? What does it represent?

**Comment by kmillet** [comment]
hmm, ok. It's  indeed not necessary as it is not a resource.

**Comment by koenedaele** [comment]
Can someone give me definitions of:

* toevalsvondsten (I assume this is not the actual find but the notification that something was found?)
* notas
* archeologienotas

And check that the one for meldingen_vooronderzoek is correct?

**Comment by jolijnleen** [comment]
Toevalsvondsten: Iedere roerend of onroerend goed, bij toeval gevonden op een ander moment dan bij het uitvoeren van een archeologisch vooronderzoek, een archeologische opgraving of het gebruik van een metaaldetector waarvan men weet of redelijkerwijs vermoedt dat het archeologische erfgoedwaarde heeft.

Archeologienota:  document, opgemaakt op basis van een archeologisch vooronderzoek, met administratieve gegevens, een verslag over de resultaten van het onderzoek, een voorstel van beslissing en een plan van aanpak voor de maatregelen die daaruit volgen; (-> nota, privacy-fiche, archeologierapport, eindverslag)

Nota: document, opgemaakt op basis van een archeologisch vooronderzoek met ingreep in de bodem dat is uitgevoerd na het bekomen van de stedenbouwkundige vergunning, met administratieve gegevens, een verslag van de resultaten van het onderzoek, een voorstel van beslissing en een plan van aanpak voor de maatregelen die daaruit volgen; (-> privacy-fiche, archeologienota, archeologierapport, eindverslag)

**Comment by koenedaele** [comment]
> Toevalsvondsten: Iedere roerend of onroerend goed, bij toeval gevonden op een ander moment dan bij het uitvoeren van een archeologisch vooronderzoek, een archeologische opgraving of het gebruik van een metaaldetector waarvan men weet of redelijkerwijs vermoedt dat het archeologische erfgoedwaarde heeft.

Dit zou willen zeggen dat wat er in de authentieke bron zit voorwerpen zijn, maar ik vermoed dat het eigenlijk meldingen van vondsten zijn? Dat één record in de databank `Toevalsvondsten` meerdere fysieke vondsten kan bevatten (bv. een kruik en 10 scherven die samen gevonden werden?). Dus dat de Authentieke Bron eigenlijk de melding van toevalsvondsten afhandelt, niet het gedetailleerd beschrijven van de vondst zelf?

**Comment by jolijnleen** [comment]
Ja correct , ik had nu gewoon de definitie voor toevalsvondsten gegeven, had niet goed door dat het over de authentieke bron ging.
 in de authentieke bron zitten dus meldingen van toevalsvondsten. Het kan ook goed zijn dat er een melding van een toevalsvondst binnenkomt maar dat dit geen archeologische erfgoedwaarde heeft en dus geen toevalsvondst is.. dit zal in het proces bepaald worden.

**Comment by jolijnleen** [comment]
Authentieke bron archeologienota en nota's: hier gaat het over het indienen van het document (zie def) + aantal metadatavelden door de erkend archeoloog.
In het daaropvolgende proces zal AOE de archeologienota/nota evalueren en een beslissing aan koppelen (bekrachtigen/bekrachtigen met voorwaarden/weigeren)

**Comment by koenedaele** [comment]
> Archeologienota:  document, opgemaakt op basis van een archeologisch vooronderzoek, met administratieve gegevens, een verslag over de resultaten van het onderzoek, een voorstel van beslissing en een plan van aanpak voor de maatregelen die daaruit volgen; (-> nota, privacy-fiche, archeologierapport, eindverslag)

Begrijp ik het goed dat dit over archeologisch vooronderzoek zonder ingreep in de bodem gaat? Dus bureauonderzoek? Ik heb zitten zoeken in het decreet maar ik kom altijd de term archeologienota tegen. Gaat dit dan over Art. 5.4.12. De archeologienota's waarbij er geen vooronderzoek met ingreep in de bodem kan plaatsvinden?

**Comment by koenedaele** [comment]
> Nota: document, opgemaakt op basis van een archeologisch vooronderzoek met ingreep in de bodem dat is uitgevoerd na het bekomen van de stedenbouwkundige vergunning, met administratieve gegevens, een verslag van de resultaten van het onderzoek, een voorstel van beslissing en een plan van aanpak voor de maatregelen die daaruit volgen; (-> privacy-fiche, archeologienota, archeologierapport, eindverslag)

En deze is dan Art. 5.4.16?

Dus, in de reguliere procedure is er enkel een archeologienota. In de speciale procedure (Onderafdeling 7) is het totaal van de archeologienota en de bijkomende nota gelijk aan de informatie uit de gewone procedure. Dus, de nota vult eingelijk de archeologienota aan met de resultaten van het vooronderzoek met ingreep in de bodem?

**Comment by koenedaele** [comment]
> > Archeologienota:  document, opgemaakt op basis van een archeologisch vooronderzoek, met administratieve gegevens, een verslag over de resultaten van het onderzoek, een voorstel van beslissing en een plan van aanpak voor de maatregelen die daaruit volgen; (-> nota, privacy-fiche, archeologierapport, eindverslag)

> Begrijp ik het goed dat dit over archeologisch vooronderzoek zonder ingreep in de bodem gaat? Dus bureauonderzoek? Ik heb zitten zoeken in het decreet maar ik kom altijd de term archeologienota tegen. Gaat dit dan over Art. 5.4.12. De archeologienota's waarbij er geen vooronderzoek met ingreep in de bodem kan plaatsvinden?

Denk niet dat ik het goed begrepen had. Archeologienota is zowel 5.4.8 als 5.4.12. Nota is 5.4.16. Archeologienota is normaal wel met ingreep in de bodem (als het uit 5.4.8 komt).

**Comment by koenedaele** [comment]
Gelieve de huidige versies van MeldingVooronderzoek, Archeologienota, ArcheologienotaNota en Toevalsvondsten te reviewen.

Ik heb gekozen voor Archeologienota en ArcheologienotaNota omdat de Nota waar we altijd over spreken een zeer generieke term is voor een zeer specifiek document. Op basis van mijn begrip van de wetgeving is de "Nota" altijd het gevolg van een Archeologienota zonder ingreep in de bodem.

**Comment by koenedaele** [comment]
Merged the first ones with Master.

**Comment by koenedaele** [comment]
Remaining:

**Meldingen aanvang (authentieke bron)**

_uris in het kader van bouwwerken:_

> https://id.erfgoed.net/archeologie/meldingen_aanvang/bouwwerken/vooronderzoek
> https://id.erfgoed.net/archeologie/meldingen_aanvang/bouwwerken/opgraving

_uris in het kader van wetenschappelijke vraagstelling:_

>https://id.erfgoed.net/archeologie/meldingen_aanvang/wetenschappelijke_vraagstelling/vooronderzoek
> https://id.erfgoed.net/archeologie/meldingen_aanvang/wetenschappelijke_vraagstelling/opgraving

**Rapporten en eindverslagen (authentieke bron)**

_uris in het kader van bouwwerken:_

> https://id.erfgoed.net/archeologie/archeologierapporten/bouwwerken
> https://id.erfgoed.net/archeologie/eindverslagen/bouwwerken

_uris in het kader van wetenschappelijke vraagstelling_

>https://id.erfgoed.net/archeologie/archeologierapporten/wetenschappelijke_vraagstelling/vooronderzoek
> https://id.erfgoed.net/archeologie/archeologierapporten/wetenschappelijke_vraagstelling/opgraving
> https://id.erfgoed.net/archeologie/eindverslagen/wetenschappelijke_vraagstelling/vooronderzoek
> https://id.erfgoed.net/archeologie/eindverslagen/wetenschappelijke_vraagstelling/opgraving


**Toelatingen (Authentieke bron)**

_uris:_

> https://id.erfgoed.net/archeologie/toelatingen/opgraving
> https://id.erfgoed.net/archeologie/toelatingen/vooronderzoek

**Comment by kmillet** [comment]
Na overleg met jou en Maarten stel ik voor dat het zo wordt:

Remaining:

**Meldingen aanvang (authentieke bron)**

_uris in het kader van bouwwerken:_

> https://id.erfgoed.net/archeologie/meldingen_aanvang_vooronderzoek_bouwwerken
> https://id.erfgoed.net/archeologie/meldingen_aanvang_opgraving_bouwwerken

_uris in het kader van wetenschappelijke vraagstelling:_

>https://id.erfgoed.net/archeologie/meldingen_aanvang_vooronderzoek_wetenschappelijke_vraagstelling
> https://id.erfgoed.net/archeologie/meldingen_aanvang_opgraving_wetenschappelijke_vraagstelling

**Rapporten en eindverslagen (authentieke bron)**

_uris in het kader van bouwwerken:_

> https://id.erfgoed.net/archeologie/archeologierapporten_bouwwerken
> https://id.erfgoed.net/archeologie/eindverslagen_bouwwerken

_uris in het kader van wetenschappelijke vraagstelling_

>https://id.erfgoed.net/archeologie/archeologierapporten_vooronderzoek_wetenschappelijke_vraagstelling
> https://id.erfgoed.net/archeologie/archeologierapporten_opgraving_wetenschappelijke_vraagstelling
> https://id.erfgoed.net/archeologie/eindverslagen_vooronderzoek_wetenschappelijke_vraagstelling
> https://id.erfgoed.net/archeologie/eindverslagen_opgraving_wetenschappelijke_vraagstelling


**Toelatingen (Authentieke bron)**

_uris:_

> https://id.erfgoed.net/archeologie/toelatingen_opgraving
> https://id.erfgoed.net/archeologie/toelatingen_vooronderzoek

**Comment by kmillet** [comment]
zie ook [https://github.com/OnroerendErfgoed/archeologieportaal/issues/8](archeologieportaal issue)

**Comment by koenedaele** [comment]
@kmillet @jolijnleen Graag de definities bij Meldingen aanvang nalezen.

**Comment by jolijnleen** [comment]
Nagelezen, en ziet er oké uit!

**Comment by koenedaele** [comment]
Meldingen aanvang ook gemerged met master.

**Comment by koenedaele** [comment]
Still remaining: Rapporten en eindverslagen en Toelatingen
