### ISSUE TITLE
Class for Dossier bijlagen

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/ontology#3]
We need an RDF Class for the bijlagen that are attached to a Dossier. Name: Bijlagen, Documenten, ...

Since they are attached to a Dossier they are not completely autonomous, so not an Authentieke Bron in their own right.

**Comment by koenedaele** [comment]
@claeyswo 

Ik zou dit graag afwerken. Op dit moment hebben we de volgende properties: 

* dos_heeftBijlage
* dos_heeftFoto
* dos_heeftBriefInkennisstelling
* dos_heeftBriefTermijnverlenging
* dos_heeftBriefEindePassiefBehoud

Drie daarvan (de brieven) zouden ook in de één of de andere vorm met een poststuk moeten kunnen. Klopt dit nog steeds? Ik zou dezelfde relaties willen behouden maar gewoon aangeven dat de relatie zowel met een poststuk als een dossierbijlage kan zijn.

Zijn dit effectief relaties van het dossier? Of eerder relaties die bij de authentieke bron toevalsvondst horen? Nu hebben ze allemaal rdfs:domain oe:Dossier, maar zijn er bij die oe:Toevalsvondst zouden moeten hebben?

**Comment by claeyswo** [comment]
Naar mijn gevoel horen die bij het dossier. Dan kunnen we nog gemakkelijk de link leggen toevalsvondst -> dossier -> brieven.

Dat van dat poststuk klopt, naamgeving lijkt mij dan wel wat raar maar die brieven zijn normaal steeds gekoppeld als poststuk en als bijlage.
