### ISSUE TITLE
Properties for Toevalsvondst and Actor

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/ontology#4]
Volgende relaties tussen Toevalsvondst en Actor zijn nodig (OnroerendErfgoed/proces_toevalsvondsten#16):

* heeft als vinder: wie heeft de vondst gedaan?
* heeft als gebruiker: wie is de gebruiker van het terrein waarop de vondst werd gedaan?
* heeft als zakelijkrechthouder: wie is de "eigenaar" van het terrein waarop de vondst werd gedaan?
* heeft als gemeente: 
* heeft als intergemeentelijk archeoloog:

Voor de eerste 3 kan ik denk ik zelf definities opstellen. De laatste 2 zijn me minder duidelijk. @jolijnleen ?

**Comment by jolijnleen** [comment]
Volgens mij in dezelfde lijn als 'gebruiker' en 'zakelijkrechthouder' (zakelijkrechthouder= 1 woord niet 2 woorden)

heeft als gemeente: Wie is de gemeente van het terrein waarop de vondst werd gedaan?
heeft als intergemeentelijk archeoloog: Wie is de intergemeentelijk archeoloog van het terrein waarop de vondst werd gedaan?

**Comment by koenedaele** [comment]
> heeft als gemeente: Wie is de gemeente van het terrein waarop de vondst werd gedaan?

Moet dit altijd de gemeente zijn of kan het ook een link naar de intergemeentelijke erfgoeddienst zijn die voor het terrein verantwoordelijk is? Of is dit een puur administratief geografisch gegeven?

**Comment by jolijnleen** [comment]
Dit staat in de wetgeving art 5.1.4. toevalsvondsten
> In voorkomend geval brengt het agentschap de zakelijkrechthouder en de gebruiker van de betrokken percelen, als ze niet de vinder zijn, en de gemeenten waar de vondsten worden gedaan ervan op de hoogte dat er vondsten zijn gedaan die vermoedelijk archeologische erfgoedwaarde hebben en wat de rechtsgevolgen daarvan zijn.

Als extra ging ook de intergemeentelijk archeoloog op de hoogte gebracht worden (puur informatief).

--> Ik ga nog eens checken of de 'gemeenten' dan ook een intergemeentelijke erfgoeddienst kan zijn, en of met intergemeentelijk archeoloog niet 'intergemeentelijke erfgoeddienst' ipv intergemeentelijk archeoloog wordt bedoeld.

**Comment by koenedaele** [comment]
Eerste 3 properties werden al toegevoegd. Ik wacht om te mergen tot er duidelijkheid is over gemeente en intergemeentelijk archeoloog.

**Comment by jolijnleen** [comment]
Gemeente : dit zijn enkel de gemeenten
Intergemeentelijk archeoloog: dit is de 'erkende intergemeentelijke onroerend erfgoeddienst'
--> Misschien is het dan beter om term 'intergemeentelijk archeoloog' aan te passen naar 'erkende intergemeentelijke onroerend erfgoeddienst' of 'erkende IOED'?

heeft als gemeente: Wie is de gemeente van het terrein waarop de vondst werd gedaan?
heeft als intergemeentelijk archeoloog `of beter heeft als erkende intergemeentelijke onroerend erfgoedddienst?` Wie is de erkende intergemeentelijk onroerend erfgoeddienst van het terrein waarop de vondst werd gedaan?

**Comment by koenedaele** [comment]
> heeft als intergemeentelijk archeoloog of beter heeft als erkende intergemeentelijke onroerend erfgoedddienst? Wie is de erkende intergemeentelijk onroerend erfgoeddienst van het terrein waarop de vondst werd gedaan?

Ik ga er van uit dat dit ook een stadsdienst kan zijn in het geval van Antwerpen of Gent? Is `heeft als onroerend erfgoeddienst` dan niet correcter? Stel ook dat ze de IOED's nog eens van naam veranderen?

**Comment by koenedaele** [comment]
Uiteindelijke conclusie, we laten het verwittigen van de IOED op dit moment vallen. Dus enkel de gemeente moet er nog bijkomen.
